export * from "./ArmedObject";
export * from "./EquipableObject";
export * from "./LimitedInteractionObject";
export * from "./MobileObject";
export * from "./MobilityModifierObject";
export * from "./OwnableObject";
export * from "./PickableObject";
export * from "./ResourceGeneratorObject";
export * from "./TreasureObject";
