export enum MapObjectId {
  Bouy = "bouy",
  Cottage = "cottage",
  FaerieRing = "faerie-ring",
  Fireplace = "fireplace",
  Fountain = "fountain",
  Gazebo = "gazebo",
  Graveyard = "graveyard",
  Hut = "hut",
  Oasis = "oasis",
  Obelisk = "obelisk",
  Rosebush = "rosebush",
  Shipwreck = "shipwreck",
  Shrine = "shrine",
  Shrine2 = "shrine2",
  Signpost = "signpost",
  Statue = "statue",
  ThatchedHut = "thatched-hut",
  TravelGate = "travel-gate",
  WagonCamp = "wagon-camp",
  Waterwheel = "waterwheel",
  Whirlpool = "whirlpool",
  Windmill = "windmill",
}
